language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
node_js:
  - "12.2.0"
before_install:
  - npm install npm -g
before_script:
  - npm install -g grunt-cli
script:
  - npm run-script ci
